// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz6rc30rMxPUXABIsF-konRaXWkour62U',
    appId: '1:146181550012:web:40556954810a705fc5c5b9',
    messagingSenderId: '146181550012',
    projectId: 'practice-f2e58',
    authDomain: 'practice-f2e58.firebaseapp.com',
    storageBucket: 'practice-f2e58.appspot.com',
    measurementId: 'G-E8VPVPHPFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8BN1MSX7v4MgZJkxSz3EBeVBIxldBriw',
    appId: '1:146181550012:android:35b239c863089643c5c5b9',
    messagingSenderId: '146181550012',
    projectId: 'practice-f2e58',
    storageBucket: 'practice-f2e58.appspot.com',
  );
}
